// Create-Mod — pure string generators for each emitted mod file. NO fs, NO images.
// Generated by `npm run create-mod`. See docs/superpowers/specs/2026-06-29-create-mod-compiler-design.md.

// Kebab mod/char id -> a valid camelCase JS identifier. Kebab stays for paths + quoted keys;
// camelId is used for every JS binding/named export (a hyphen in an identifier is a SyntaxError).
export function toCamelId(id) {
  return String(id).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

// `normalized.name` (mod title) can originate from an LLM's --from-book synthesis over
// untrusted book text (src/createmod/smart/index.js -> extractFacts's modTitle). Every header
// below interpolates it RAW into a `//` line comment; a line terminator in it would close the
// comment and let the rest of the string become executable JS in a generated mods/<id>/*.js
// file that runs in the game client. Collapse every ECMAScript LineTerminator (the exact set
// that ends a `//` comment: \r, \n, U+2028, U+2029) to a single space before interpolating any
// untrusted string into a generated-JS comment header. JSON.stringify'd values (e.g. tagline,
// version) are already safe and do NOT need this — they're proper string literals, not raw text.
const LINE_TERMINATORS = new RegExp('[\\r\\n\\u2028\\u2029]+', 'g');
function headerSafe(s) {
  return String(s).replace(LINE_TERMINATORS, ' ');
}

export function dataJson(normalized) {
  const obj = { roster: normalized.roster, lore: normalized.lore };
  if (normalized.mapType === 'atlas') obj.world = normalized.world;
  else obj.map = normalized.map;
  return JSON.stringify(obj, null, 2) + '\n';
}

export function charactersDataJs(normalized) {
  return `// ${headerSafe(normalized.name)} — character data (server-safe, NO portrait imports). Generated by create-mod.
import { RULES } from '../dominion/rules';
import data from './${normalized.id}.data.json';

export const CHARACTERS_DATA = data.roster;

export function getCharacterById(id) {
  return CHARACTERS_DATA.find(c => c.id === id);
}

export function getStartingMoney(character) {
  return RULES.core.baseStartingMoney + character.stats.capital * RULES.stats.capital.startingMoneyBonus;
}
`;
}

export function loreJs(normalized) {
  return `// ${headerSafe(normalized.name)} — character lore (server-safe). Generated by create-mod.
import data from './${normalized.id}.data.json';

export const CHARACTER_LORE = data.lore;

export function getLoreById(id) {
  return CHARACTER_LORE[id] || null;
}
`;
}

export function bundleDataJs(normalized) {
  const camel = toCamelId(normalized.id);
  const isAtlas = normalized.mapType === 'atlas';
  return `// ${headerSafe(normalized.name)} — Tier-A bundle (server/test-safe). NO image imports. Generated by create-mod.
import { RULES } from '../dominion/rules';
import { BOARD_SPACES, COLOR_GROUPS } from '../dominion/board';
import { CHANCE_CARDS, COMMUNITY_CARDS } from '../dominion/cards';
import { CHARACTERS_DATA, getCharacterById, getStartingMoney } from './characters-data';
import { CHARACTER_LORE, getLoreById } from './lore';
import data from './${normalized.id}.data.json';

export const ${camel}Data = {
  id: '${normalized.id}',
  name: ${JSON.stringify(normalized.name)},
  tagline: ${JSON.stringify(normalized.tagline || '')},
  version: ${JSON.stringify(normalized.version || '1.0.0')},

  rules: RULES,
  characters: CHARACTERS_DATA,
  board: { spaces: BOARD_SPACES, colorGroups: COLOR_GROUPS },
  cards: { chance: CHANCE_CARDS, community: COMMUNITY_CARDS },
  lore: CHARACTER_LORE,

  getCharacterById,
  getStartingMoney,
  getLoreById,

  maps: ${isAtlas ? '[]' : '[data.map]'},
  worlds: ${isAtlas ? '[data.world]' : '[]'},
};

export default ${camel}Data;
`;
}

export function charactersJs(normalized) {
  const portraits = normalized.portraits || [];
  const ext = p => p.path.slice(p.path.lastIndexOf('.'));
  const importLines = portraits.map(p => `import ${toCamelId(p.id)} from './portraits/${p.id}${ext(p)}';`).join('\n');
  const mapLines = portraits.map(p => `  '${p.id}': ${toCamelId(p.id)},`).join('\n');
  return `// ${headerSafe(normalized.name)} — client character data (with portraits). Generated by create-mod.
import { CHARACTERS_DATA, getCharacterById, getStartingMoney } from './characters-data';
${importLines ? importLines + '\n' : ''}
const PORTRAIT_MAP = {
${mapLines}
};

export const CHARACTERS = CHARACTERS_DATA.map(char => ({
  ...char,
  portrait: PORTRAIT_MAP[char.id] || null,
}));

export { getCharacterById, getStartingMoney };
`;
}

export function bundleClientJs(normalized) {
  const camel = toCamelId(normalized.id);
  const mapImage = normalized.world && typeof normalized.world.mapImage === 'string' ? normalized.world.mapImage : null;
  const worldBgExt = mapImage ? mapImage.slice(mapImage.lastIndexOf('.')) : null;
  const worldBgImport = mapImage ? `import worldBg from './worldbg${worldBgExt}';\n` : '';
  // cityImages:{} is REQUIRED: App.js derefs assets.cityImages[placeId] unguarded whenever
  // an atlasAssets entry exists — the empty map falls back to plain color tiles.
  const atlasAssetsExpr = mapImage
    ? `{ '${normalized.world.id}': { worldBg, cityImages: {} } }`
    : '{}';
  return `// ${headerSafe(normalized.name)} — Tier-B bundle (CLIENT only). Layers images over Tier-A. Generated by create-mod.
// NEVER import from Game.js / server.js / the sim / tests (pulls the keyArt PNG + globe lib).
import { ${camel}Data } from './bundle.data';
import { CHARACTERS } from './characters';
import keyArt from '../dominion/keyart.png';
${worldBgImport}import { getGlobe } from '../dominion/atlas/globe-lib';

export const ${camel}Client = Object.assign({}, ${camel}Data, {
  characters: CHARACTERS,
  portraits: {},
  keyArt: keyArt,
  atlasAssets: ${atlasAssetsExpr},
  getGlobe: getGlobe,
});

export default ${camel}Client;
`;
}
