// Create-Mod — pure string generators for each emitted mod file. NO fs, NO images.
// Generated by `npm run create-mod`. See docs/superpowers/specs/2026-06-29-create-mod-compiler-design.md.

// Kebab mod/char id -> a valid camelCase JS identifier. Kebab stays for paths + quoted keys;
// camelId is used for every JS binding/named export (a hyphen in an identifier is a SyntaxError).
export function toCamelId(id) {
  return String(id).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}
